
services:
  # User Management Service - uses shared infrastructure services
  user-management-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-management-service
    environment:
      # Spring Profile
      SPRING_PROFILES_ACTIVE: local
      
      # Authentication feature flag
      SKISHOP_AUTHFUNC_ENABLE: "false"
      
      # Database settings - using shared PostgreSQL
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/skishop_user?autoCommit=false
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_HIKARI_AUTO_COMMIT: "false"
      
      # Redis settings - using shared Redis
      SPRING_DATA_REDIS_HOST: host.docker.internal
      SPRING_DATA_REDIS_PORT: 6379
      
      # JVM settings
      JAVA_OPTS: "-Xmx512m -Xms256m -Djava.security.egd=file:/dev/./urandom"
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

# User Management Service uses shared infrastructure services
# PostgreSQL, Redis, etc. are provided by ../.devcontainer/docker-compose.yml
# This service connects to shared services via host network
