
services:
  # Payment Cart Service - uses shared infrastructure services
  payment-cart-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-cart-service
    environment:
      # Database configuration - using shared PostgreSQL
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/skishop_payment
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      
      # Redis configuration - using shared Redis
      SPRING_DATA_REDIS_HOST: host.docker.internal
      SPRING_DATA_REDIS_PORT: 6379
      
      # Kafka configuration - using shared Kafka
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: host.docker.internal:9092
      
      # Stripe configuration (development keys)
      STRIPE_API_KEY: sk_test_dummy_key_for_development
      STRIPE_WEBHOOK_SECRET: whsec_dummy_secret_for_development
      
      # Security configuration (for local development)
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://localhost:8080/auth/realms/skishop
      
      # JVM configuration
      JAVA_OPTS: "-Xms256m -Xmx512m"
    volumes:
      - ./logs:/app/logs
    network_mode: host
    restart: unless-stopped

# Payment Cart Service uses shared infrastructure services
# PostgreSQL, Redis, Kafka, etc. are provided by ../.devcontainer/docker-compose.yml
# This service connects to shared services via host network
