
services:
  # Sales Management Service - uses shared infrastructure services
  sales-management-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sales-management-service
    environment:
      # Database configuration - using shared PostgreSQL
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/skishop_sales
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      
      # Redis configuration - using shared Redis
      SPRING_DATA_REDIS_HOST: host.docker.internal
      SPRING_DATA_REDIS_PORT: 6379
      
      # Kafka configuration - using shared Kafka
      SPRING_KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
      
      # JVM configuration
      JAVA_OPTS: "-Xms256m -Xmx512m"
    network_mode: host
    restart: unless-stopped

# Sales Management Service uses shared infrastructure services
# PostgreSQL, Redis, Kafka, etc. are provided by ../.devcontainer/docker-compose.yml
# This service connects to shared services via host network
