# Azure OpenAI Configuration Example
# Please modify the configuration values according to your environment

spring:
  application:
    name: ai-support-service

# Azure OpenAI Settings - Environment Variables Required
azure:
  openai:
    api-key: ${AZURE_OPENAI_KEY:your-api-key}
    endpoint: ${AZURE_OPENAI_ENDPOINT:https://your-resource.openai.azure.com/}
    deployment-name: ${AZURE_OPENAI_DEPLOYMENT_NAME:gpt-4o}
    embedding-deployment-name: ${AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME:text-embedding-3-small}
    api-version: ${AZURE_OPENAI_API_VERSION:2024-02-15-preview}
    timeout: 60s
    max-retries: 3
    temperature: 0.7
    max-tokens: 2000

# Environment Variables Example:
# AZURE_OPENAI_KEY=your-actual-api-key
# AZURE_OPENAI_ENDPOINT=https://your-resource.openai.azure.com/
# AZURE_OPENAI_DEPLOYMENT_NAME=gpt-4o
# AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME=text-embedding-3-small
