
services:
  # Coupon Service - uses shared infrastructure services
  coupon-service:
    build: .
    container_name: coupon-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      
      # Database configuration - using shared PostgreSQL
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/coupon_db
      
      # Redis configuration - using shared Redis
      SPRING_DATA_REDIS_HOST: host.docker.internal
      SPRING_DATA_REDIS_PORT: 6379
      
      # Kafka configuration - using shared Kafka
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: host.docker.internal:9092
    volumes:
      - ./logs:/app/logs
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

# Coupon Service uses shared infrastructure services
# PostgreSQL, Redis, Kafka, etc. are provided by ../.devcontainer/docker-compose.yml
# This service connects to shared services via host network
