spring:
  application:
    name: user-management-service
  
  # Local development database settings
  datasource:
    url: jdbc:postgresql://postgres:5432/skishop_user
    username: skishop_user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 20000
      validation-timeout: 5000
      leak-detection-threshold: 60000
      auto-commit: false
  
  # JPA settings
  jpa:
    hibernate:
      ddl-auto: create-drop # Auto-create for local
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': true
        '[use_sql_comments]': true
        '[jdbc.batch_size]': 20
        '[order_inserts]': true
        '[order_updates]': true
        '[globally_quoted_identifiers]': false
        '[globally_quoted_identifiers_skip_column_definitions]': true
        connection:
          auto-commit: false
    open-in-view: false
    defer-datasource-initialization: true
  
  # Transaction management
  transaction:
    default-timeout: 30
    rollback-on-commit-failure: true
  
  # Flyway disabled (using JPA auto-create)
  flyway:
    enabled: false
  
  # Redis settings
  data:
    redis:
      host: redis
      port: 6379
      password: 
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# Server settings
server:
  port: 8081
  servlet:
    context-path: /api

# Management endpoint settings
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,mappings
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

# Logging settings (for local)
logging:
  level:
    '[com.skishop.user]': DEBUG
    '[org.springframework.security]': INFO
    '[org.springframework.web]': INFO
    '[org.hibernate.SQL]': DEBUG
    '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE
    '[org.springframework.data.redis]': DEBUG
    '[io.github.resilience4j]': DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Application specific settings (local)
skishop:
  # Authentication feature flag (enable authentication)
  authfunc:
    enable: ${SKISHOP_AUTH_ENABLE:true}
    
  user:
    # Password settings (relaxed for local)
    password:
      min-length: 4
      max-length: 100
      require-uppercase: false
      require-lowercase: false
      require-digits: false
      require-special-chars: false
    
    # Email verification settings (disabled for local)
    email-verification:
      token-validity: 24 # hours
      base-url: http://localhost:3000
      
    # Account lock settings (disabled for local)
    account-lock:
      max-failed-attempts: 999
      lock-duration: 1 # minutes
    
    # Notification settings (disabled for local)
    notification:
      email:
        enabled: false
  
  # Event Propagation Configuration for Local Development
  runtime:
    event-propagation-enabled: true
    event-broker-type: redis
    event-max-retries: 3
    event-timeout-ms: 30000
    event-redis-key-prefix: skishop-local
    event-concurrency: 2
    event-persistence-enabled: true
    processed-event-retention-days: 7
    debug-mode: true
    environment: local

# API documentation settings
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  packages-to-scan: com.skishop.user.controller


