server:
  port: 8083

spring:
  application:
    name: sales-management-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/skishop_sales
    username: ${DB_USERNAME:skishop_user}
    password: ${DB_PASSWORD:skishop_password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
    consumer:
      group-id: sales-management-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "*"
  
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    com.skishop.sales: DEBUG
    org.springframework.kafka: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Application specific settings
app:
  order:
    expiry-hours: 24  # Order expiration time (hours)
    auto-cancel-enabled: true  # Auto-cancel feature
  
  shipping:
    free-shipping-threshold: 5000  # Free shipping threshold
    default-shipping-fee: 500  # Default shipping fee
  
  return:
    allowed-days: 30  # Allowed return days
    auto-approval-threshold: 10000  # Auto-approval threshold
  
  kafka:
    topics:
      orders: sales.orders
      shipments: sales.shipments
      returns: sales.returns

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
